### ISSUE TITLE
back-up mdstree and mdsnode in XML files

### ISSUE THREAD

**Issue by drsmith48** [Fusion-Data-Platform/fdp#33]
I've found 2 instances of common signals changing trees and/or nodes in the transition from NSTX to NSTX-U:
- The high-n mirnov array was previously in OPS_PC tree, and now it's in FASTMAG tree
- The D-alpha signals (and filtered visible, more broadly) have new node names and tags (but still in PASSIVESPEC tree)

I propose implementing XML elements and container/signal attributes like `mdstree2` and `mdsnode2`.  If the data call with `mdstree` and `mdsnode` fails, then Machine._get_mdsdata() will try the 2nd set.  Thoughts?

**Comment by ktritz** [comment]
this might be better handled with a shot number check and a preprocessing
utility function. If the shot number is lower than the start of nstx-u,
then it replaces the mdsnode/tree with the old value.

**Comment by drsmith48** [comment]
I implemented pre-processing for magnetics in pull request #34 .
