### ISSUE TITLE
point_axes not working

### ISSUE THREAD

**Issue by ktritz** [Fusion-Data-Platform/fdp#48]
normal operations, not just returning sliced signals, removes axes and populates point_axes:

nstx = fdp.nstx()
Attempting logbook server connection as drsmith

nstx.s141398.mpts.ne.point_axes
Out[62]: []

nstx.s141398.mpts.ne
Out[63]: 
SignalMpts([[  8.61600344e+17,   2.02931343e+18,   1.76151548e+18, ...,
          3.88446934e+17,   3.31107387e+17,   2.60636351e+17],
       [  2.95658535e+18,   6.89444188e+18,   5.85341457e+18, ...,
          1.25780555e+18,   1.24557077e+18,   1.32392961e+18],
       [  4.89410711e+18,   1.13892788e+19,   1.00899322e+19, ...,
          1.15486749e+18,   4.52337720e+17,   1.53583240e+17],
       ..., 
       [  1.65356214e+19,   2.66311194e+19,   3.09732581e+19, ...,
          8.38575291e+18,   5.93253327e+18,   4.70896517e+17],
       [  9.88455166e+18,   1.42157597e+19,   1.58881834e+19, ...,
          3.87875690e+18,   2.70177460e+18,   1.85761022e+18],
       [  2.33479317e+19,   1.44183371e+19,   1.43488301e+19, ...,
          3.58928745e+18,   1.72633758e+18,   1.42310547e+17]])

nstx.s141398.mpts.ne.point_axes
Out[64]: 
[{'axis': 'time', 'units': 's', 'value': 0.014998018741607666},
 {'axis': 'radius', 'units': 'm', 'value': 0.38919675350189209}]

nstx.s141398.mpts.ne.axes
Out[65]: []

This issue might be that we need to make and return explicit copies of the signals when they get sliced, otherwise the axes manipulations will affect the original signals. Not quite sure what the best resolution is for this.

**Comment by drsmith48** [comment]
fixed in PR #51  (I think)
